# Project information
site_name: "Documentation 'payme-pkg'"
site_description: 🟢 Merchant Api and Subscribe Api Integration 2023—08
site_author: Hoosnick
site_url: https://hoosnick.github.io/payme-pkg
docs_dir: docs/src
site_dir: docs

# Repository
repo_name: hoosnick/payme-pkg
repo_url: https://hoosnick.github.io/payme-pkg
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 PayTechUz

# Configuration
theme:
  name: material
  custom_dir: docs/src/overrides
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono
  icon:
    logo: material/cash-multiple
  # logo: assets/logo.png

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+7Gn-JZ99TfgwZDNi
      name: "Biz telegramda"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/PayTechUz/payme-pkg
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - meta
  - attr_list
  - toc:
      permalink: true

nav:
  - "home": index.md
  - "interaction_setup": setup.md
  - "merchant_api": merchant-api.md
  - "subscribe_api": subscribe-api.md
  - "sandbox": sandbox.md
  - "support": support.md

plugins:
  - search
  - i18n:
      default_language: en
      default_language_only: false
      docs_structure: folder

      languages:
        en:
          name: "<img style='height: 10px; border: 0px;'' alt='en' src='https://flagicons.lipis.dev/flags/4x3/us.svg' title='english' /> English"
          build: true
        uz:
          name: "<img style='height: 10px; border: 0px;' alt='uz' src='https://flagicons.lipis.dev/flags/4x3/uz.svg' title='uzbek' /> O'zbekcha"
          build: true
        ru:
          name: "<img style='height: 10px; border: 0px;'' alt='ru' src='https://flagicons.lipis.dev/flags/4x3/ru.svg' title='russian' /> Русский"
          build: true
          site_name: "Документация 'payme-pkg'"

      nav_translations:
        en:
          "home": "Introduction"
          "interaction_setup": "Interaction setup"
          "merchant_api": "Merchant API"
          "subscribe_api": "Subscribe API"
          "sandbox": "Sandbox (Testing)"
          "support": "Technical support"
        ru:
          "home": "Введение"
          "interaction_setup": "Настройка взаимодействия"
          "merchant_api": "Merchant API"
          "subscribe_api": "Subscribe API"
          "sandbox": "Песочница (Тестирование)"
          "support": "Техническая поддержка"
        uz:
          "home": "Kirish"
          "interaction_setup": "Sozlash (Setup)"
          "merchant_api": "Merchant API"
          "subscribe_api": "Subscribe API"
          "sandbox": "Qumdon (Sandbox)"
          "support": "Texnik yordam"
